 (function(){
    start = performance.now()
    document.getElementById("output").pivotUI(
        [
            {color: "blue", shape: "circle"},
            {color: "red", shape: "triangle"},
            {color: "green", shape: "square"},
            {color: "yellow", shape: "rectangle"},
            {color: "orange", shape: "pentagon"},
            {color: "indigo", shape: "octagon"},
            {color: "violet", shape: "octagon"},
            {color: "blue", shape: "circle"},
            {color: "red", shape: "triangle"},
            {color: "green", shape: "square"},
            {color: "yellow", shape: "rectangle"},
            {color: "orange", shape: "pentagon"},
            {color: "indigo", shape: "octagon"},
            {color: "violet", shape: "octagon"},
            {color: "blue", shape: "circle"},
            {color: "red", shape: "triangle"},
            {color: "green", shape: "square"},
            {color: "yellow", shape: "rectangle"},
            {color: "orange", shape: "pentagon"},
            {color: "indigo", shape: "octagon"},
            {color: "violet", shape: "octagon"},
            {color: "blue", shape: "circle"},
            {color: "red", shape: "triangle"},
            {color: "green", shape: "square"},
            {color: "yellow", shape: "rectangle"},
            {color: "orange", shape: "pentagon"},
            {color: "indigo", shape: "octagon"},
            {color: "violet", shape: "octagon"},
            {color: "blue", shape: "circle"},
            {color: "red", shape: "triangle"},
            {color: "green", shape: "square"},
            {color: "yellow", shape: "rectangle"},
            {color: "orange", shape: "pentagon"},
            {color: "indigo", shape: "octagon"},
            {color: "violet", shape: "octagon"},
            {color: "blue", shape: "circle"},
            {color: "red", shape: "triangle"},
            {color: "green", shape: "square"},
            {color: "yellow", shape: "rectangle"},
            {color: "orange", shape: "pentagon"},
            {color: "indigo", shape: "octagon"},
            {color: "violet", shape: "octagon"},
            {color: "blue", shape: "circle"},
            {color: "red", shape: "triangle"},
            {color: "green", shape: "square"},
            {color: "yellow", shape: "rectangle"},
            {color: "orange", shape: "pentagon"},
            {color: "indigo", shape: "octagon"},
            {color: "violet", shape: "octagon"},
            {color: "blue", shape: "circle"},
            {color: "red", shape: "triangle"},
            {color: "green", shape: "square"},
            {color: "yellow", shape: "rectangle"},
            {color: "orange", shape: "pentagon"},
            {color: "indigo", shape: "octagon"},
            {color: "violet", shape: "octagon"},
            {color: "blue", shape: "circle"},
            {color: "red", shape: "triangle"},
            {color: "green", shape: "square"},
            {color: "yellow", shape: "rectangle"},
            {color: "orange", shape: "pentagon"},
            {color: "indigo", shape: "octagon"},
            {color: "violet", shape: "octagon"},
            {color: "blue", shape: "circle"},
            {color: "red", shape: "triangle"},
            {color: "green", shape: "square"},
            {color: "yellow", shape: "rectangle"},
            {color: "orange", shape: "pentagon"},
            {color: "indigo", shape: "octagon"},
            {color: "violet", shape: "octagon"},
            {color: "blue", shape: "circle"},
            {color: "red", shape: "triangle"},
            {color: "green", shape: "square"},
            {color: "yellow", shape: "rectangle"},
            {color: "orange", shape: "pentagon"},
            {color: "indigo", shape: "octagon"},
            {color: "violet", shape: "octagon"},
            {color: "blue", shape: "circle"},
            {color: "red", shape: "triangle"},
            {color: "green", shape: "square"},
            {color: "yellow", shape: "rectangle"},
            {color: "orange", shape: "pentagon"},
            {color: "indigo", shape: "octagon"},
            {color: "violet", shape: "octagon"}
        ],
        {
            rows: ["color"],
            cols: ["shape"],
        }
    );
    end = performance.now()
    console.log(end-start)
 })();